{
  "version": "1.0",
  "selection": {
    "topics": [
      "Operators",
      "Control Structures",
      "Functions",
      "Data Structures",
      "Modules and Packages",
      "File Handling"
    ],
    "min_difficulty": "easy",
    "max_difficulty": "hard",
    "total_questions": 20,
    "questions": [],
    "question_types": [
      "code_completion",
      "debugging",
      "algorithm_design"
    ]
  }
}