question_types:
  - name: code_completion
    description: "Complete partial code implementations"
    examples:
      easy:
        - "Complete this function to calculate factorial"
        - "Implement basic arithmetic operations"
      medium:
        - "Implement a decorator with specific behavior"
        - "Handle file I/O operations"
      hard:
        - "Write a context manager for resource handling"
        - "Implement async/await patterns"

  - name: debugging
    description: "Identify and fix code errors"
    examples:
      easy:
        - "Find syntax errors in code snippet"
        - "Fix variable name typos"
      medium:
        - "Debug logical errors in algorithm"
        - "Resolve type mismatch issues"
      hard:
        - "Diagnose race conditions in concurrent code"
        - "Fix memory leaks in long-running processes"

  - name: algorithm_design
    description: "Create solutions to computational problems"
    examples:
      easy:
        - "Implement basic sorting algorithm"
        - "Create simple data structures"
      medium:
        - "Design graph traversal solution"
        - "Optimize search algorithms"
      hard:
        - "Create distributed system consensus algorithm"
        - "Develop machine learning pipelines"
